name: Merge Checks

on:
  merge_group:

jobs:
  merge-checks:
    name: Merge Checks
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Build, Test, and Lint
        uses: remedyred/check-action@v1.2.8
        with:
          SCRIPTS: ci
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREVENT_COMMITS: true
