<<<<<<<< HEAD:.github/workflows/merge-checks.yml
name: Merge Checks

on:
  merge_group:

jobs:
  merge-checks:
    name: Merge Checks
========
name: PR Checks

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main,dev,next]

jobs:
  pr-checks:
    name: PR Checks
>>>>>>>> ba12247 (ci: update remedyred/release-please-action and workflows):.github/workflows/pr-checks.yml
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Build, test, and verify
        uses: remedyred/release-please-action@v1.8.8
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PRERELEASE_ONLY: true
<<<<<<<< HEAD:.github/workflows/merge-checks.yml
          PRERELEASE_SCRIPTS: build,test,fix,docs
========
          PRERELEASE_SCRIPTS: build,test,fix
>>>>>>>> ba12247 (ci: update remedyred/release-please-action and workflows):.github/workflows/pr-checks.yml
